cmake_minimum_required(VERSION 3.21)
project(ra-base C)

include(GNUInstallDirs)

set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)

add_library(ra-base SHARED base.c)
install(TARGETS ra-base
	ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
	LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
	RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)
install(FILES ra_base.h DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
